application: omega-tabster
version: beta
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

error_handlers:
  - file: templates/500.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /img/*.png
  static_dir: static/img
  mime_type: image/png

- url: /img/*
  static_dir: static/img

- url: /js/*
  static_dir: static/js

- url: /css/*
  static_dir: static/css

- url: /bundle/*
  static_dir: static/bundle

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /api/v1/.+
  script: main.app

- url: /admin
  script: main.app
  login: admin

- url: /a/.*
  script: main.app
  login: required

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?.*\.pyc$
